sudo: false
language: node_js
node_js:
  - '8'
  - '9'
  - '10'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
  - npm run coveralls
